services:
  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./web:/var/www/html  # WordPress lee de aquí
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - db

git:
    image: alpine/git
    volumes:
      - ./web:/repo
    working_dir: /repo
    entrypoint: ["sh"]
    command: 
      -c "git config --global --add safe.directory /repo && ([ -d .git ] || git init && git remote add origin https://github.com/ProyectoAmpliacion/ProyectoAmpliacion.git) && git fetch origin && git checkout origin/main -- index.php && rm -rf .git"

volumes:
  db_data:
